server:
  shutdown: graceful
  port: 8080

spring:
  pid:
    file: server.pid
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/spacei
      username: spacei
      password: ENC(RtRgyL11F8oXVfoc9ic8wLiZ4GDv1rG8)
      ## space12!@#
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 659754322905-qglt5anks2qqcdkn1e22jo46fn01f8ig.apps.googleusercontent.com
            client-secret: ENC(9OIQDUegz5eyb2bE5QjYlXr8qDGGvQ7LNJYUi6yfXrJV1mRtQrLNS13cdW256z2n)
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile,email
          naver:
            client-id: QX2BY7T7WQRSQwBIXrGV
            client-secret: ENC(3g+2XVASZnt7lw3Uwk8pL2871kbKUO1G)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name-attribute: response
  sql:
    init:
      mode: always
      data-locations: classpath:sql/init.sql


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: tk # JASYPT_ENCRYPTOR_PASSWORD


springdoc:
  packages-to-scan: com.hack
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    enabled: true

space:
  openai-key: ENC(wy6xPCx6vIkDkoD7YQcjT1xtzwpny6Rdhv47teep8eS/IG++miXF0/67+AP20jMcKd2UZryCGrZsieBrCy+g7w==)
